// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: gateway/v1/errors.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 用户登录失败，可能是用户名或密码不对
	ErrorReason_UserLoginFailed ErrorReason = 0
	// 用户已存在错误
	ErrorReason_UserAlreadyExists ErrorReason = 1
	// 用户未找到错误
	ErrorReason_UserNotFound ErrorReason = 2
	// 创建用户失败错误
	ErrorReason_UserCreateFailed ErrorReason = 3
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "UserLoginFailed",
		1: "UserAlreadyExists",
		2: "UserNotFound",
		3: "UserCreateFailed",
	}
	ErrorReason_value = map[string]int32{
		"UserLoginFailed":   0,
		"UserAlreadyExists": 1,
		"UserNotFound":      2,
		"UserCreateFailed":  3,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_gateway_v1_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_gateway_v1_errors_proto protoreflect.FileDescriptor

const file_gateway_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x17gateway/v1/errors.proto\x12\n" +
	"gateway.v1\x1a\x13errors/errors.proto*\x7f\n" +
	"\vErrorReason\x12\x19\n" +
	"\x0fUserLoginFailed\x10\x00\x1a\x04\xa8E\x91\x03\x12\x1b\n" +
	"\x11UserAlreadyExists\x10\x01\x1a\x04\xa8E\x99\x03\x12\x16\n" +
	"\fUserNotFound\x10\x02\x1a\x04\xa8E\x94\x03\x12\x1a\n" +
	"\x10UserCreateFailed\x10\x03\x1a\x04\xa8E\x9d\x04\x1a\x04\xa0E\xf4\x03B4Z2github.com/LiangNing7/minerx/pkg/api/gateway/v1;v1b\x06proto3"

var (
	file_gateway_v1_errors_proto_rawDescOnce sync.Once
	file_gateway_v1_errors_proto_rawDescData []byte
)

func file_gateway_v1_errors_proto_rawDescGZIP() []byte {
	file_gateway_v1_errors_proto_rawDescOnce.Do(func() {
		file_gateway_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_errors_proto_rawDesc), len(file_gateway_v1_errors_proto_rawDesc)))
	})
	return file_gateway_v1_errors_proto_rawDescData
}

var file_gateway_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_v1_errors_proto_goTypes = []any{
	(ErrorReason)(0), // 0: gateway.v1.ErrorReason
}
var file_gateway_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_v1_errors_proto_init() }
func file_gateway_v1_errors_proto_init() {
	if File_gateway_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_errors_proto_rawDesc), len(file_gateway_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_errors_proto_goTypes,
		DependencyIndexes: file_gateway_v1_errors_proto_depIdxs,
		EnumInfos:         file_gateway_v1_errors_proto_enumTypes,
	}.Build()
	File_gateway_v1_errors_proto = out.File
	file_gateway_v1_errors_proto_goTypes = nil
	file_gateway_v1_errors_proto_depIdxs = nil
}
