// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: gateway/v1/gateway.proto

package v1

import (
	v1beta1 "github.com/LiangNing7/minerx/pkg/apis/apps/v1beta1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdempotentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdempotentRequest) Reset() {
	*x = IdempotentRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotentRequest) ProtoMessage() {}

func (x *IdempotentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotentRequest.ProtoReflect.Descriptor instead.
func (*IdempotentRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type IdempotentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdempotentResponse) Reset() {
	*x = IdempotentResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotentResponse) ProtoMessage() {}

func (x *IdempotentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotentResponse.ProtoReflect.Descriptor instead.
func (*IdempotentResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *IdempotentResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitVersion    string                 `protobuf:"bytes,1,opt,name=GitVersion,proto3" json:"GitVersion,omitempty"`
	GitCommit     string                 `protobuf:"bytes,2,opt,name=GitCommit,proto3" json:"GitCommit,omitempty"`
	GitTreeState  string                 `protobuf:"bytes,3,opt,name=GitTreeState,proto3" json:"GitTreeState,omitempty"`
	BuildDate     string                 `protobuf:"bytes,4,opt,name=BuildDate,proto3" json:"BuildDate,omitempty"`
	GoVersion     string                 `protobuf:"bytes,5,opt,name=GoVersion,proto3" json:"GoVersion,omitempty"`
	Compiler      string                 `protobuf:"bytes,6,opt,name=Compiler,proto3" json:"Compiler,omitempty"`
	Platform      string                 `protobuf:"bytes,7,opt,name=Platform,proto3" json:"Platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GetVersionResponse) GetGitVersion() string {
	if x != nil {
		return x.GitVersion
	}
	return ""
}

func (x *GetVersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *GetVersionResponse) GetGitTreeState() string {
	if x != nil {
		return x.GitTreeState
	}
	return ""
}

func (x *GetVersionResponse) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

func (x *GetVersionResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *GetVersionResponse) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *GetVersionResponse) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1capps/v1beta1/generated.proto\x1a\x16gateway/v1/miner.proto\x1a\x19gateway/v1/minerset.proto\"\x13\n" +
	"\x11IdempotentRequest\"*\n" +
	"\x12IdempotentResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x13\n" +
	"\x11GetVersionRequest\"\xea\x01\n" +
	"\x12GetVersionResponse\x12\x1e\n" +
	"\n" +
	"GitVersion\x18\x01 \x01(\tR\n" +
	"GitVersion\x12\x1c\n" +
	"\tGitCommit\x18\x02 \x01(\tR\tGitCommit\x12\"\n" +
	"\fGitTreeState\x18\x03 \x01(\tR\fGitTreeState\x12\x1c\n" +
	"\tBuildDate\x18\x04 \x01(\tR\tBuildDate\x12\x1c\n" +
	"\tGoVersion\x18\x05 \x01(\tR\tGoVersion\x12\x1a\n" +
	"\bCompiler\x18\x06 \x01(\tR\bCompiler\x12\x1a\n" +
	"\bPlatform\x18\a \x01(\tR\bPlatform2\x94\r\n" +
	"\aGateway\x12]\n" +
	"\n" +
	"GetVersion\x12\x1d.gateway.v1.GetVersionRequest\x1a\x1e.gateway.v1.GetVersionResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/version\x12l\n" +
	"\x12GetIdempotentToken\x12\x1d.gateway.v1.IdempotentRequest\x1a\x1e.gateway.v1.IdempotentResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/idempotents\x12\xa6\x01\n" +
	"\x0eCreateMinerSet\x12<.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet\x1a<.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/minersets\x12\xa6\x01\n" +
	"\x0eUpdateMinerSet\x12<.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet\x1a<.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/minersets\x12u\n" +
	"\x0eDeleteMinerSet\x12!.gateway.v1.DeleteMinerSetRequest\x1a\".gateway.v1.DeleteMinerSetResponse\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/v1/minersets/{name}\x12\x89\x01\n" +
	"\vGetMinerSet\x12\x1e.gateway.v1.GetMinerSetRequest\x1a<.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/minersets/{name}\x12h\n" +
	"\fListMinerSet\x12\x1f.gateway.v1.ListMinerSetRequest\x1a .gateway.v1.ListMinerSetResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/minersets\x12{\n" +
	"\rScaleMinerSet\x12 .gateway.v1.ScaleMinerSetRequest\x1a!.gateway.v1.ScaleMinerSetResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/v1/minersets/{name}/scale\x12\x9a\x01\n" +
	"\vCreateMiner\x129.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner\x1a9.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/miners\x12\x9a\x01\n" +
	"\vUpdateMiner\x129.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner\x1a9.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\x1a\n" +
	"/v1/miners\x12i\n" +
	"\vDeleteMiner\x12\x1e.gateway.v1.DeleteMinerRequest\x1a\x1f.gateway.v1.DeleteMinerResponse\"\x19\x82\xd3\xe4\x93\x02\x13*\x11/v1/miners/{name}\x12}\n" +
	"\bGetMiner\x12\x1b.gateway.v1.GetMinerRequest\x1a9.github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/miners/{name}\x12\\\n" +
	"\tListMiner\x12\x1c.gateway.v1.ListMinerRequest\x1a\x1d.gateway.v1.ListMinerResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/minersB4Z2github.com/LiangNing7/minerx/pkg/api/gateway/v1;v1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*IdempotentRequest)(nil),      // 0: gateway.v1.IdempotentRequest
	(*IdempotentResponse)(nil),     // 1: gateway.v1.IdempotentResponse
	(*GetVersionRequest)(nil),      // 2: gateway.v1.GetVersionRequest
	(*GetVersionResponse)(nil),     // 3: gateway.v1.GetVersionResponse
	(*v1beta1.MinerSet)(nil),       // 4: github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet
	(*DeleteMinerSetRequest)(nil),  // 5: gateway.v1.DeleteMinerSetRequest
	(*GetMinerSetRequest)(nil),     // 6: gateway.v1.GetMinerSetRequest
	(*ListMinerSetRequest)(nil),    // 7: gateway.v1.ListMinerSetRequest
	(*ScaleMinerSetRequest)(nil),   // 8: gateway.v1.ScaleMinerSetRequest
	(*v1beta1.Miner)(nil),          // 9: github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner
	(*DeleteMinerRequest)(nil),     // 10: gateway.v1.DeleteMinerRequest
	(*GetMinerRequest)(nil),        // 11: gateway.v1.GetMinerRequest
	(*ListMinerRequest)(nil),       // 12: gateway.v1.ListMinerRequest
	(*DeleteMinerSetResponse)(nil), // 13: gateway.v1.DeleteMinerSetResponse
	(*ListMinerSetResponse)(nil),   // 14: gateway.v1.ListMinerSetResponse
	(*ScaleMinerSetResponse)(nil),  // 15: gateway.v1.ScaleMinerSetResponse
	(*DeleteMinerResponse)(nil),    // 16: gateway.v1.DeleteMinerResponse
	(*ListMinerResponse)(nil),      // 17: gateway.v1.ListMinerResponse
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	2,  // 0: gateway.v1.Gateway.GetVersion:input_type -> gateway.v1.GetVersionRequest
	0,  // 1: gateway.v1.Gateway.GetIdempotentToken:input_type -> gateway.v1.IdempotentRequest
	4,  // 2: gateway.v1.Gateway.CreateMinerSet:input_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet
	4,  // 3: gateway.v1.Gateway.UpdateMinerSet:input_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet
	5,  // 4: gateway.v1.Gateway.DeleteMinerSet:input_type -> gateway.v1.DeleteMinerSetRequest
	6,  // 5: gateway.v1.Gateway.GetMinerSet:input_type -> gateway.v1.GetMinerSetRequest
	7,  // 6: gateway.v1.Gateway.ListMinerSet:input_type -> gateway.v1.ListMinerSetRequest
	8,  // 7: gateway.v1.Gateway.ScaleMinerSet:input_type -> gateway.v1.ScaleMinerSetRequest
	9,  // 8: gateway.v1.Gateway.CreateMiner:input_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner
	9,  // 9: gateway.v1.Gateway.UpdateMiner:input_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner
	10, // 10: gateway.v1.Gateway.DeleteMiner:input_type -> gateway.v1.DeleteMinerRequest
	11, // 11: gateway.v1.Gateway.GetMiner:input_type -> gateway.v1.GetMinerRequest
	12, // 12: gateway.v1.Gateway.ListMiner:input_type -> gateway.v1.ListMinerRequest
	3,  // 13: gateway.v1.Gateway.GetVersion:output_type -> gateway.v1.GetVersionResponse
	1,  // 14: gateway.v1.Gateway.GetIdempotentToken:output_type -> gateway.v1.IdempotentResponse
	4,  // 15: gateway.v1.Gateway.CreateMinerSet:output_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet
	4,  // 16: gateway.v1.Gateway.UpdateMinerSet:output_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet
	13, // 17: gateway.v1.Gateway.DeleteMinerSet:output_type -> gateway.v1.DeleteMinerSetResponse
	4,  // 18: gateway.v1.Gateway.GetMinerSet:output_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.MinerSet
	14, // 19: gateway.v1.Gateway.ListMinerSet:output_type -> gateway.v1.ListMinerSetResponse
	15, // 20: gateway.v1.Gateway.ScaleMinerSet:output_type -> gateway.v1.ScaleMinerSetResponse
	9,  // 21: gateway.v1.Gateway.CreateMiner:output_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner
	9,  // 22: gateway.v1.Gateway.UpdateMiner:output_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner
	16, // 23: gateway.v1.Gateway.DeleteMiner:output_type -> gateway.v1.DeleteMinerResponse
	9,  // 24: gateway.v1.Gateway.GetMiner:output_type -> github.com.LiangNing7.minerx.pkg.apis.apps.v1beta1.Miner
	17, // 25: gateway.v1.Gateway.ListMiner:output_type -> gateway.v1.ListMinerResponse
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	file_gateway_v1_miner_proto_init()
	file_gateway_v1_minerset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
