// This file defines the Protobuf messages for managing Miners.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: gateway/v1/miner.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Miner represents a miner with its metadata.
type Miner struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	MinerType   string                 `protobuf:"bytes,3,opt,name=minerType,proto3" json:"minerType,omitempty"`
	ChainName   string                 `protobuf:"bytes,4,opt,name=chainName,proto3" json:"chainName,omitempty"`
	DataDir     string                 `protobuf:"bytes,5,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	Status      string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// CreatedAt is the timestamp when the miner was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// UpdatedAt is the timestamp when the miner was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Miner) Reset() {
	*x = Miner{}
	mi := &file_gateway_v1_miner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Miner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Miner) ProtoMessage() {}

func (x *Miner) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Miner.ProtoReflect.Descriptor instead.
func (*Miner) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{0}
}

func (x *Miner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Miner) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Miner) GetMinerType() string {
	if x != nil {
		return x.MinerType
	}
	return ""
}

func (x *Miner) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *Miner) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

func (x *Miner) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Miner) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Miner) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateMinerRequest represents the request message for creating a new miner.
type CreateMinerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DisplayName   string                 `protobuf:"bytes,1,opt,name=displayName,proto3" json:"displayName,omitempty"`
	MinerType     string                 `protobuf:"bytes,2,opt,name=minerType,proto3" json:"minerType,omitempty"`
	ChainName     string                 `protobuf:"bytes,3,opt,name=chainName,proto3" json:"chainName,omitempty"`
	DataDir       string                 `protobuf:"bytes,4,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMinerRequest) Reset() {
	*x = CreateMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMinerRequest) ProtoMessage() {}

func (x *CreateMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMinerRequest.ProtoReflect.Descriptor instead.
func (*CreateMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMinerRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateMinerRequest) GetMinerType() string {
	if x != nil {
		return x.MinerType
	}
	return ""
}

func (x *CreateMinerRequest) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *CreateMinerRequest) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

// UpdateMinerRequest represents the request message for updating an existing miner.
type UpdateMinerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	DeletePolicy  *string                `protobuf:"bytes,3,opt,name=deletePolicy,proto3,oneof" json:"deletePolicy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMinerRequest) Reset() {
	*x = UpdateMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMinerRequest) ProtoMessage() {}

func (x *UpdateMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMinerRequest.ProtoReflect.Descriptor instead.
func (*UpdateMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateMinerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMinerRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateMinerRequest) GetDeletePolicy() string {
	if x != nil && x.DeletePolicy != nil {
		return *x.DeletePolicy
	}
	return ""
}

// DeleteMinerRequest represents the request message for deleting one or more miners.
type DeleteMinerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMinerRequest) Reset() {
	*x = DeleteMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMinerRequest) ProtoMessage() {}

func (x *DeleteMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMinerRequest.ProtoReflect.Descriptor instead.
func (*DeleteMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteMinerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteMinerResponse represents the response message for a successful miner deletion.
type DeleteMinerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMinerResponse) Reset() {
	*x = DeleteMinerResponse{}
	mi := &file_gateway_v1_miner_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMinerResponse) ProtoMessage() {}

func (x *DeleteMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMinerResponse.ProtoReflect.Descriptor instead.
func (*DeleteMinerResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{4}
}

// GetMinerRequest represents the request message for retrieving a specific miner.
type GetMinerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier of the miner to retrieve.
	// @gotags: uri:"name"
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" uri:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMinerRequest) Reset() {
	*x = GetMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinerRequest) ProtoMessage() {}

func (x *GetMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinerRequest.ProtoReflect.Descriptor instead.
func (*GetMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{5}
}

func (x *GetMinerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetMinerResponse represents the response message for a successful retrieval of a miner.
type GetMinerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Miner is the retrieved miner object.
	Miner         *Miner `protobuf:"bytes,1,opt,name=miner,proto3" json:"miner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMinerResponse) Reset() {
	*x = GetMinerResponse{}
	mi := &file_gateway_v1_miner_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinerResponse) ProtoMessage() {}

func (x *GetMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinerResponse.ProtoReflect.Descriptor instead.
func (*GetMinerResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{6}
}

func (x *GetMinerResponse) GetMiner() *Miner {
	if x != nil {
		return x.Miner
	}
	return nil
}

// ListMinerRequest represents the request message for listing miners
// with pagination and optional filters.
type ListMinerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the starting point of the list for pagination.
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// Limit is the maximum number of miners to return.
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMinerRequest) Reset() {
	*x = ListMinerRequest{}
	mi := &file_gateway_v1_miner_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMinerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMinerRequest) ProtoMessage() {}

func (x *ListMinerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMinerRequest.ProtoReflect.Descriptor instead.
func (*ListMinerRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{7}
}

func (x *ListMinerRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMinerRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListMinerResponse represents the response message for listing miners.
type ListMinerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TotalCount is the total number of miners matching the query.
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// Miner is the list of miners in the current page.
	Miners        []*Miner `protobuf:"bytes,2,rep,name=miners,proto3" json:"miners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMinerResponse) Reset() {
	*x = ListMinerResponse{}
	mi := &file_gateway_v1_miner_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMinerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMinerResponse) ProtoMessage() {}

func (x *ListMinerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_miner_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMinerResponse.ProtoReflect.Descriptor instead.
func (*ListMinerResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_miner_proto_rawDescGZIP(), []int{8}
}

func (x *ListMinerResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMinerResponse) GetMiners() []*Miner {
	if x != nil {
		return x.Miners
	}
	return nil
}

var File_gateway_v1_miner_proto protoreflect.FileDescriptor

const file_gateway_v1_miner_proto_rawDesc = "" +
	"\n" +
	"\x16gateway/v1/miner.proto\x12\n" +
	"gateway.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x02\n" +
	"\x05Miner\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12\x1c\n" +
	"\tminerType\x18\x03 \x01(\tR\tminerType\x12\x1c\n" +
	"\tchainName\x18\x04 \x01(\tR\tchainName\x12\x18\n" +
	"\adataDir\x18\x05 \x01(\tR\adataDir\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x128\n" +
	"\tcreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8c\x01\n" +
	"\x12CreateMinerRequest\x12 \n" +
	"\vdisplayName\x18\x01 \x01(\tR\vdisplayName\x12\x1c\n" +
	"\tminerType\x18\x02 \x01(\tR\tminerType\x12\x1c\n" +
	"\tchainName\x18\x03 \x01(\tR\tchainName\x12\x18\n" +
	"\adataDir\x18\x04 \x01(\tR\adataDir\"\x99\x01\n" +
	"\x12UpdateMinerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdisplayName\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12'\n" +
	"\fdeletePolicy\x18\x03 \x01(\tH\x01R\fdeletePolicy\x88\x01\x01B\x0e\n" +
	"\f_displayNameB\x0f\n" +
	"\r_deletePolicy\"(\n" +
	"\x12DeleteMinerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13DeleteMinerResponse\"%\n" +
	"\x0fGetMinerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x10GetMinerResponse\x12'\n" +
	"\x05miner\x18\x01 \x01(\v2\x11.gateway.v1.MinerR\x05miner\"@\n" +
	"\x10ListMinerRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"T\n" +
	"\x11ListMinerResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12)\n" +
	"\x06miners\x18\x02 \x03(\v2\x11.gateway.v1.MinerR\x06minersB4Z2github.com/LiangNing7/minerx/pkg/api/gateway/v1;v1b\x06proto3"

var (
	file_gateway_v1_miner_proto_rawDescOnce sync.Once
	file_gateway_v1_miner_proto_rawDescData []byte
)

func file_gateway_v1_miner_proto_rawDescGZIP() []byte {
	file_gateway_v1_miner_proto_rawDescOnce.Do(func() {
		file_gateway_v1_miner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_miner_proto_rawDesc), len(file_gateway_v1_miner_proto_rawDesc)))
	})
	return file_gateway_v1_miner_proto_rawDescData
}

var file_gateway_v1_miner_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_gateway_v1_miner_proto_goTypes = []any{
	(*Miner)(nil),                 // 0: gateway.v1.Miner
	(*CreateMinerRequest)(nil),    // 1: gateway.v1.CreateMinerRequest
	(*UpdateMinerRequest)(nil),    // 2: gateway.v1.UpdateMinerRequest
	(*DeleteMinerRequest)(nil),    // 3: gateway.v1.DeleteMinerRequest
	(*DeleteMinerResponse)(nil),   // 4: gateway.v1.DeleteMinerResponse
	(*GetMinerRequest)(nil),       // 5: gateway.v1.GetMinerRequest
	(*GetMinerResponse)(nil),      // 6: gateway.v1.GetMinerResponse
	(*ListMinerRequest)(nil),      // 7: gateway.v1.ListMinerRequest
	(*ListMinerResponse)(nil),     // 8: gateway.v1.ListMinerResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_gateway_v1_miner_proto_depIdxs = []int32{
	9, // 0: gateway.v1.Miner.createdAt:type_name -> google.protobuf.Timestamp
	9, // 1: gateway.v1.Miner.updatedAt:type_name -> google.protobuf.Timestamp
	0, // 2: gateway.v1.GetMinerResponse.miner:type_name -> gateway.v1.Miner
	0, // 3: gateway.v1.ListMinerResponse.miners:type_name -> gateway.v1.Miner
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_v1_miner_proto_init() }
func file_gateway_v1_miner_proto_init() {
	if File_gateway_v1_miner_proto != nil {
		return
	}
	file_gateway_v1_miner_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_miner_proto_rawDesc), len(file_gateway_v1_miner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_miner_proto_goTypes,
		DependencyIndexes: file_gateway_v1_miner_proto_depIdxs,
		MessageInfos:      file_gateway_v1_miner_proto_msgTypes,
	}.Build()
	File_gateway_v1_miner_proto = out.File
	file_gateway_v1_miner_proto_goTypes = nil
	file_gateway_v1_miner_proto_depIdxs = nil
}
