// This file defines the Protobuf messages for managing MinerSets.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: gateway/v1/minerset.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MinerTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinerType     string                 `protobuf:"bytes,1,opt,name=minerType,proto3" json:"minerType,omitempty"`
	ChainName     string                 `protobuf:"bytes,2,opt,name=chainName,proto3" json:"chainName,omitempty"`
	DataDir       string                 `protobuf:"bytes,3,opt,name=dataDir,proto3" json:"dataDir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinerTemplate) Reset() {
	*x = MinerTemplate{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerTemplate) ProtoMessage() {}

func (x *MinerTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerTemplate.ProtoReflect.Descriptor instead.
func (*MinerTemplate) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{0}
}

func (x *MinerTemplate) GetMinerType() string {
	if x != nil {
		return x.MinerType
	}
	return ""
}

func (x *MinerTemplate) GetChainName() string {
	if x != nil {
		return x.ChainName
	}
	return ""
}

func (x *MinerTemplate) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

// MinerSet represents a minerset with its metadata.
type MinerSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	DeletePolicy  string                 `protobuf:"bytes,4,opt,name=deletePolicy,proto3" json:"deletePolicy,omitempty"`
	MinerTemplate *MinerTemplate         `protobuf:"bytes,5,opt,name=MinerTemplate,proto3" json:"MinerTemplate,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinerSet) Reset() {
	*x = MinerSet{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerSet) ProtoMessage() {}

func (x *MinerSet) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerSet.ProtoReflect.Descriptor instead.
func (*MinerSet) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{1}
}

func (x *MinerSet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MinerSet) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *MinerSet) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MinerSet) GetDeletePolicy() string {
	if x != nil {
		return x.DeletePolicy
	}
	return ""
}

func (x *MinerSet) GetMinerTemplate() *MinerTemplate {
	if x != nil {
		return x.MinerTemplate
	}
	return nil
}

func (x *MinerSet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MinerSet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateMinerSetRequest represents the request message for creating a new minerset.
type CreateMinerSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      int32                  `protobuf:"varint,1,opt,name=replicas,proto3" json:"replicas,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=displayName,proto3" json:"displayName,omitempty"`
	DeletePolicy  string                 `protobuf:"bytes,3,opt,name=deletePolicy,proto3" json:"deletePolicy,omitempty"`
	MinerTemplate *MinerTemplate         `protobuf:"bytes,4,opt,name=MinerTemplate,proto3" json:"MinerTemplate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMinerSetRequest) Reset() {
	*x = CreateMinerSetRequest{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMinerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMinerSetRequest) ProtoMessage() {}

func (x *CreateMinerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMinerSetRequest.ProtoReflect.Descriptor instead.
func (*CreateMinerSetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMinerSetRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *CreateMinerSetRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateMinerSetRequest) GetDeletePolicy() string {
	if x != nil {
		return x.DeletePolicy
	}
	return ""
}

func (x *CreateMinerSetRequest) GetMinerTemplate() *MinerTemplate {
	if x != nil {
		return x.MinerTemplate
	}
	return nil
}

// UpdateMinerSetRequest represents the request message for updating an existing minerset.
type UpdateMinerSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   *string                `protobuf:"bytes,2,opt,name=displayName,proto3,oneof" json:"displayName,omitempty"`
	DeletePolicy  *string                `protobuf:"bytes,3,opt,name=deletePolicy,proto3,oneof" json:"deletePolicy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMinerSetRequest) Reset() {
	*x = UpdateMinerSetRequest{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMinerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMinerSetRequest) ProtoMessage() {}

func (x *UpdateMinerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMinerSetRequest.ProtoReflect.Descriptor instead.
func (*UpdateMinerSetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMinerSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMinerSetRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateMinerSetRequest) GetDeletePolicy() string {
	if x != nil && x.DeletePolicy != nil {
		return *x.DeletePolicy
	}
	return ""
}

// DeleteMinerSetRequest represents the request message for deleting one or more minersets.
type DeleteMinerSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMinerSetRequest) Reset() {
	*x = DeleteMinerSetRequest{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMinerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMinerSetRequest) ProtoMessage() {}

func (x *DeleteMinerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMinerSetRequest.ProtoReflect.Descriptor instead.
func (*DeleteMinerSetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteMinerSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DeleteMinerSetResponse represents the response message for a successful minerset deletion.
type DeleteMinerSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMinerSetResponse) Reset() {
	*x = DeleteMinerSetResponse{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMinerSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMinerSetResponse) ProtoMessage() {}

func (x *DeleteMinerSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMinerSetResponse.ProtoReflect.Descriptor instead.
func (*DeleteMinerSetResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{5}
}

// GetMinerSetRequest represents the request message for retrieving a specific minerset.
type GetMinerSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the unique identifier of the minerset to retrieve.
	// @gotags: uri:"name"
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty" uri:"name"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMinerSetRequest) Reset() {
	*x = GetMinerSetRequest{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinerSetRequest) ProtoMessage() {}

func (x *GetMinerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinerSetRequest.ProtoReflect.Descriptor instead.
func (*GetMinerSetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{6}
}

func (x *GetMinerSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// GetMinerSetResponse represents the response message for a successful retrieval of a minerset.
type GetMinerSetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MinerSet is the retrieved minerset object.
	MinerSet      *MinerSet `protobuf:"bytes,1,opt,name=minerSet,proto3" json:"minerSet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMinerSetResponse) Reset() {
	*x = GetMinerSetResponse{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinerSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinerSetResponse) ProtoMessage() {}

func (x *GetMinerSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinerSetResponse.ProtoReflect.Descriptor instead.
func (*GetMinerSetResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{7}
}

func (x *GetMinerSetResponse) GetMinerSet() *MinerSet {
	if x != nil {
		return x.MinerSet
	}
	return nil
}

// ListMinerSetRequest represents the request message for listing minersets
// with pagination and optional filters.
type ListMinerSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Offset is the starting point of the list for pagination.
	// @gotags: form:"offset"
	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// Limit is the maximum number of minersets to return.
	// @gotags: form:"limit"
	Limit         int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMinerSetRequest) Reset() {
	*x = ListMinerSetRequest{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMinerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMinerSetRequest) ProtoMessage() {}

func (x *ListMinerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMinerSetRequest.ProtoReflect.Descriptor instead.
func (*ListMinerSetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{8}
}

func (x *ListMinerSetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListMinerSetRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListMinerSetResponse represents the response message for listing minersets.
type ListMinerSetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// TotalCount is the total number of minersets matching the query.
	Total int64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	// MinerSet is the list of minersets in the current page.
	MinerSets     []*MinerSet `protobuf:"bytes,2,rep,name=minerSets,proto3" json:"minerSets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMinerSetResponse) Reset() {
	*x = ListMinerSetResponse{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMinerSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMinerSetResponse) ProtoMessage() {}

func (x *ListMinerSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMinerSetResponse.ProtoReflect.Descriptor instead.
func (*ListMinerSetResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{9}
}

func (x *ListMinerSetResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMinerSetResponse) GetMinerSets() []*MinerSet {
	if x != nil {
		return x.MinerSets
	}
	return nil
}

type ScaleMinerSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Replicas      int32                  `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleMinerSetRequest) Reset() {
	*x = ScaleMinerSetRequest{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleMinerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleMinerSetRequest) ProtoMessage() {}

func (x *ScaleMinerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleMinerSetRequest.ProtoReflect.Descriptor instead.
func (*ScaleMinerSetRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{10}
}

func (x *ScaleMinerSetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaleMinerSetRequest) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

type ScaleMinerSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaleMinerSetResponse) Reset() {
	*x = ScaleMinerSetResponse{}
	mi := &file_gateway_v1_minerset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaleMinerSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaleMinerSetResponse) ProtoMessage() {}

func (x *ScaleMinerSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_minerset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaleMinerSetResponse.ProtoReflect.Descriptor instead.
func (*ScaleMinerSetResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_minerset_proto_rawDescGZIP(), []int{11}
}

var File_gateway_v1_minerset_proto protoreflect.FileDescriptor

const file_gateway_v1_minerset_proto_rawDesc = "" +
	"\n" +
	"\x19gateway/v1/minerset.proto\x12\n" +
	"gateway.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\rMinerTemplate\x12\x1c\n" +
	"\tminerType\x18\x01 \x01(\tR\tminerType\x12\x1c\n" +
	"\tchainName\x18\x02 \x01(\tR\tchainName\x12\x18\n" +
	"\adataDir\x18\x03 \x01(\tR\adataDir\"\xb5\x02\n" +
	"\bMinerSet\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\x12 \n" +
	"\vdisplayName\x18\x03 \x01(\tR\vdisplayName\x12\"\n" +
	"\fdeletePolicy\x18\x04 \x01(\tR\fdeletePolicy\x12?\n" +
	"\rMinerTemplate\x18\x05 \x01(\v2\x19.gateway.v1.MinerTemplateR\rMinerTemplate\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xba\x01\n" +
	"\x15CreateMinerSetRequest\x12\x1a\n" +
	"\breplicas\x18\x01 \x01(\x05R\breplicas\x12 \n" +
	"\vdisplayName\x18\x02 \x01(\tR\vdisplayName\x12\"\n" +
	"\fdeletePolicy\x18\x03 \x01(\tR\fdeletePolicy\x12?\n" +
	"\rMinerTemplate\x18\x04 \x01(\v2\x19.gateway.v1.MinerTemplateR\rMinerTemplate\"\x9c\x01\n" +
	"\x15UpdateMinerSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdisplayName\x18\x02 \x01(\tH\x00R\vdisplayName\x88\x01\x01\x12'\n" +
	"\fdeletePolicy\x18\x03 \x01(\tH\x01R\fdeletePolicy\x88\x01\x01B\x0e\n" +
	"\f_displayNameB\x0f\n" +
	"\r_deletePolicy\"+\n" +
	"\x15DeleteMinerSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16DeleteMinerSetResponse\"(\n" +
	"\x12GetMinerSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"\x13GetMinerSetResponse\x120\n" +
	"\bminerSet\x18\x01 \x01(\v2\x14.gateway.v1.MinerSetR\bminerSet\"C\n" +
	"\x13ListMinerSetRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"`\n" +
	"\x14ListMinerSetResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x122\n" +
	"\tminerSets\x18\x02 \x03(\v2\x14.gateway.v1.MinerSetR\tminerSets\"F\n" +
	"\x14ScaleMinerSetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\breplicas\x18\x02 \x01(\x05R\breplicas\"\x17\n" +
	"\x15ScaleMinerSetResponseB4Z2github.com/LiangNing7/minerx/pkg/api/gateway/v1;v1b\x06proto3"

var (
	file_gateway_v1_minerset_proto_rawDescOnce sync.Once
	file_gateway_v1_minerset_proto_rawDescData []byte
)

func file_gateway_v1_minerset_proto_rawDescGZIP() []byte {
	file_gateway_v1_minerset_proto_rawDescOnce.Do(func() {
		file_gateway_v1_minerset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_minerset_proto_rawDesc), len(file_gateway_v1_minerset_proto_rawDesc)))
	})
	return file_gateway_v1_minerset_proto_rawDescData
}

var file_gateway_v1_minerset_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gateway_v1_minerset_proto_goTypes = []any{
	(*MinerTemplate)(nil),          // 0: gateway.v1.MinerTemplate
	(*MinerSet)(nil),               // 1: gateway.v1.MinerSet
	(*CreateMinerSetRequest)(nil),  // 2: gateway.v1.CreateMinerSetRequest
	(*UpdateMinerSetRequest)(nil),  // 3: gateway.v1.UpdateMinerSetRequest
	(*DeleteMinerSetRequest)(nil),  // 4: gateway.v1.DeleteMinerSetRequest
	(*DeleteMinerSetResponse)(nil), // 5: gateway.v1.DeleteMinerSetResponse
	(*GetMinerSetRequest)(nil),     // 6: gateway.v1.GetMinerSetRequest
	(*GetMinerSetResponse)(nil),    // 7: gateway.v1.GetMinerSetResponse
	(*ListMinerSetRequest)(nil),    // 8: gateway.v1.ListMinerSetRequest
	(*ListMinerSetResponse)(nil),   // 9: gateway.v1.ListMinerSetResponse
	(*ScaleMinerSetRequest)(nil),   // 10: gateway.v1.ScaleMinerSetRequest
	(*ScaleMinerSetResponse)(nil),  // 11: gateway.v1.ScaleMinerSetResponse
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_gateway_v1_minerset_proto_depIdxs = []int32{
	0,  // 0: gateway.v1.MinerSet.MinerTemplate:type_name -> gateway.v1.MinerTemplate
	12, // 1: gateway.v1.MinerSet.createdAt:type_name -> google.protobuf.Timestamp
	12, // 2: gateway.v1.MinerSet.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: gateway.v1.CreateMinerSetRequest.MinerTemplate:type_name -> gateway.v1.MinerTemplate
	1,  // 4: gateway.v1.GetMinerSetResponse.minerSet:type_name -> gateway.v1.MinerSet
	1,  // 5: gateway.v1.ListMinerSetResponse.minerSets:type_name -> gateway.v1.MinerSet
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_gateway_v1_minerset_proto_init() }
func file_gateway_v1_minerset_proto_init() {
	if File_gateway_v1_minerset_proto != nil {
		return
	}
	file_gateway_v1_minerset_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_minerset_proto_rawDesc), len(file_gateway_v1_minerset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_v1_minerset_proto_goTypes,
		DependencyIndexes: file_gateway_v1_minerset_proto_depIdxs,
		MessageInfos:      file_gateway_v1_minerset_proto_msgTypes,
	}.Build()
	File_gateway_v1_minerset_proto = out.File
	file_gateway_v1_minerset_proto_goTypes = nil
	file_gateway_v1_minerset_proto_depIdxs = nil
}
