// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: cacheserver/v1/errors.proto

package v1

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	// 订单找不到 ，可能是订单不存在或输入的订单标识有误
	ErrorReason_OrderNotFound ErrorReason = 0
	// 订单已存在，无法创建用户
	ErrorReason_OrderAlreadyExists ErrorReason = 1
	// 创建订单失败，可能是由于服务器或其他问题导致的创建过程中的错误
	ErrorReason_OrderCreateFailed ErrorReason = 2
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "OrderNotFound",
		1: "OrderAlreadyExists",
		2: "OrderCreateFailed",
	}
	ErrorReason_value = map[string]int32{
		"OrderNotFound":      0,
		"OrderAlreadyExists": 1,
		"OrderCreateFailed":  2,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_cacheserver_v1_errors_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_cacheserver_v1_errors_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_cacheserver_v1_errors_proto_rawDescGZIP(), []int{0}
}

var File_cacheserver_v1_errors_proto protoreflect.FileDescriptor

const file_cacheserver_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x1bcacheserver/v1/errors.proto\x12\x0ecacheserver.v1\x1a\x13errors/errors.proto*g\n" +
	"\vErrorReason\x12\x17\n" +
	"\rOrderNotFound\x10\x00\x1a\x04\xa8E\x94\x03\x12\x1c\n" +
	"\x12OrderAlreadyExists\x10\x01\x1a\x04\xa8E\x99\x03\x12\x1b\n" +
	"\x11OrderCreateFailed\x10\x02\x1a\x04\xa8E\x9d\x04\x1a\x04\xa0E\xf4\x03B8Z6github.com/LiangNing7/minerx/pkg/api/cacheserver/v1;v1b\x06proto3"

var (
	file_cacheserver_v1_errors_proto_rawDescOnce sync.Once
	file_cacheserver_v1_errors_proto_rawDescData []byte
)

func file_cacheserver_v1_errors_proto_rawDescGZIP() []byte {
	file_cacheserver_v1_errors_proto_rawDescOnce.Do(func() {
		file_cacheserver_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cacheserver_v1_errors_proto_rawDesc), len(file_cacheserver_v1_errors_proto_rawDesc)))
	})
	return file_cacheserver_v1_errors_proto_rawDescData
}

var file_cacheserver_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cacheserver_v1_errors_proto_goTypes = []any{
	(ErrorReason)(0), // 0: cacheserver.v1.ErrorReason
}
var file_cacheserver_v1_errors_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cacheserver_v1_errors_proto_init() }
func file_cacheserver_v1_errors_proto_init() {
	if File_cacheserver_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cacheserver_v1_errors_proto_rawDesc), len(file_cacheserver_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cacheserver_v1_errors_proto_goTypes,
		DependencyIndexes: file_cacheserver_v1_errors_proto_depIdxs,
		EnumInfos:         file_cacheserver_v1_errors_proto_enumTypes,
	}.Build()
	File_cacheserver_v1_errors_proto = out.File
	file_cacheserver_v1_errors_proto_goTypes = nil
	file_cacheserver_v1_errors_proto_depIdxs = nil
}
