// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *SetSecretRequest) Default() {
}

func (x *DelSecretRequest) Default() {
}

func (x *GetSecretRequest) Default() {
}

func (x *GetSecretResponse) Default() {
}
