// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: toyblc/v1/toyblc.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBlockRequest) Reset() {
	*x = CreateBlockRequest{}
	mi := &file_toyblc_v1_toyblc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlockRequest) ProtoMessage() {}

func (x *CreateBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_toyblc_v1_toyblc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlockRequest.ProtoReflect.Descriptor instead.
func (*CreateBlockRequest) Descriptor() ([]byte, []int) {
	return file_toyblc_v1_toyblc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBlockRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type CreatePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePeerRequest) Reset() {
	*x = CreatePeerRequest{}
	mi := &file_toyblc_v1_toyblc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePeerRequest) ProtoMessage() {}

func (x *CreatePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_toyblc_v1_toyblc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePeerRequest.ProtoReflect.Descriptor instead.
func (*CreatePeerRequest) Descriptor() ([]byte, []int) {
	return file_toyblc_v1_toyblc_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePeerRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

var File_toyblc_v1_toyblc_proto protoreflect.FileDescriptor

const file_toyblc_v1_toyblc_proto_rawDesc = "" +
	"\n" +
	"\x16toyblc/v1/toyblc.proto\x12\ttoyblc.v1\"(\n" +
	"\x12CreateBlockRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"'\n" +
	"\x11CreatePeerRequest\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peerB3Z1github.com/LiangNing7/minerx/pkg/api/toyblc/v1;v1b\x06proto3"

var (
	file_toyblc_v1_toyblc_proto_rawDescOnce sync.Once
	file_toyblc_v1_toyblc_proto_rawDescData []byte
)

func file_toyblc_v1_toyblc_proto_rawDescGZIP() []byte {
	file_toyblc_v1_toyblc_proto_rawDescOnce.Do(func() {
		file_toyblc_v1_toyblc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_toyblc_v1_toyblc_proto_rawDesc), len(file_toyblc_v1_toyblc_proto_rawDesc)))
	})
	return file_toyblc_v1_toyblc_proto_rawDescData
}

var file_toyblc_v1_toyblc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_toyblc_v1_toyblc_proto_goTypes = []any{
	(*CreateBlockRequest)(nil), // 0: toyblc.v1.CreateBlockRequest
	(*CreatePeerRequest)(nil),  // 1: toyblc.v1.CreatePeerRequest
}
var file_toyblc_v1_toyblc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_toyblc_v1_toyblc_proto_init() }
func file_toyblc_v1_toyblc_proto_init() {
	if File_toyblc_v1_toyblc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_toyblc_v1_toyblc_proto_rawDesc), len(file_toyblc_v1_toyblc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toyblc_v1_toyblc_proto_goTypes,
		DependencyIndexes: file_toyblc_v1_toyblc_proto_depIdxs,
		MessageInfos:      file_toyblc_v1_toyblc_proto_msgTypes,
	}.Build()
	File_toyblc_v1_toyblc_proto = out.File
	file_toyblc_v1_toyblc_proto_goTypes = nil
	file_toyblc_v1_toyblc_proto_depIdxs = nil
}
