// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.1
// source: usercenter/v1/usercenter.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_usercenter_v1_usercenter_proto protoreflect.FileDescriptor

const file_usercenter_v1_usercenter_proto_rawDesc = "" +
	"\n" +
	"\x1eusercenter/v1/usercenter.proto\x12\rusercenter.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1ausercenter/v1/secret.proto\x1a\x18usercenter/v1/user.proto\x1a\x18usercenter/v1/auth.proto2\xd3\x0e\n" +
	"\n" +
	"UserCenter\x12Z\n" +
	"\x05Login\x12\x1b.usercenter.v1.LoginRequest\x1a\x19.usercenter.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12a\n" +
	"\x06Logout\x12\x1c.usercenter.v1.LogoutRequest\x1a\x1d.usercenter.v1.LogoutResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/auth/logout\x12p\n" +
	"\fRefreshToken\x12\".usercenter.v1.RefreshTokenRequest\x1a\x19.usercenter.v1.LoginReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/auth/refresh-token\x12y\n" +
	"\fAuthenticate\x12\".usercenter.v1.AuthenticateRequest\x1a#.usercenter.v1.AuthenticateResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/auth/authenticate\x12m\n" +
	"\tAuthorize\x12\x1f.usercenter.v1.AuthorizeRequest\x1a .usercenter.v1.AuthorizeResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/auth/authorize\x12Y\n" +
	"\x04Auth\x12\x1a.usercenter.v1.AuthRequest\x1a\x1b.usercenter.v1.AuthResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/auth/auth\x12g\n" +
	"\n" +
	"CreateUser\x12 .usercenter.v1.CreateUserRequest\x1a!.usercenter.v1.CreateUserResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/users\x12p\n" +
	"\n" +
	"UpdateUser\x12 .usercenter.v1.UpdateUserRequest\x1a!.usercenter.v1.UpdateUserResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/users/{userID}\x12m\n" +
	"\n" +
	"DeleteUser\x12 .usercenter.v1.DeleteUserRequest\x1a!.usercenter.v1.DeleteUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/users/{userID}\x12d\n" +
	"\aGetUser\x12\x1d.usercenter.v1.GetUserRequest\x1a\x1e.usercenter.v1.GetUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/users/{userID}\x12^\n" +
	"\bListUser\x12\x1e.usercenter.v1.ListUserRequest\x1a\x1f.usercenter.v1.ListUserResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12\x8c\x01\n" +
	"\x0eUpdatePassword\x12$.usercenter.v1.UpdatePasswordRequest\x1a%.usercenter.v1.UpdatePasswordResponse\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/v1/users/{userID}/update-password\x12o\n" +
	"\fCreateSecret\x12\".usercenter.v1.CreateSecretRequest\x1a#.usercenter.v1.CreateSecretResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/secrets\x12v\n" +
	"\fUpdateSecret\x12\".usercenter.v1.UpdateSecretRequest\x1a#.usercenter.v1.UpdateSecretResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/v1/secrets/{name}\x12s\n" +
	"\fDeleteSecret\x12\".usercenter.v1.DeleteSecretRequest\x1a#.usercenter.v1.DeleteSecretResponse\"\x1a\x82\xd3\xe4\x93\x02\x14*\x12/v1/secrets/{name}\x12j\n" +
	"\tGetSecret\x12\x1f.usercenter.v1.GetSecretRequest\x1a .usercenter.v1.GetSecretResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/secrets/{name}\x12f\n" +
	"\n" +
	"ListSecret\x12 .usercenter.v1.ListSecretRequest\x1a!.usercenter.v1.ListSecretResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/secretsB7Z5github.com/LiangNing7/minerx/pkg/api/usercenter/v1;v1b\x06proto3"

var file_usercenter_v1_usercenter_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: usercenter.v1.LoginRequest
	(*LogoutRequest)(nil),          // 1: usercenter.v1.LogoutRequest
	(*RefreshTokenRequest)(nil),    // 2: usercenter.v1.RefreshTokenRequest
	(*AuthenticateRequest)(nil),    // 3: usercenter.v1.AuthenticateRequest
	(*AuthorizeRequest)(nil),       // 4: usercenter.v1.AuthorizeRequest
	(*AuthRequest)(nil),            // 5: usercenter.v1.AuthRequest
	(*CreateUserRequest)(nil),      // 6: usercenter.v1.CreateUserRequest
	(*UpdateUserRequest)(nil),      // 7: usercenter.v1.UpdateUserRequest
	(*DeleteUserRequest)(nil),      // 8: usercenter.v1.DeleteUserRequest
	(*GetUserRequest)(nil),         // 9: usercenter.v1.GetUserRequest
	(*ListUserRequest)(nil),        // 10: usercenter.v1.ListUserRequest
	(*UpdatePasswordRequest)(nil),  // 11: usercenter.v1.UpdatePasswordRequest
	(*CreateSecretRequest)(nil),    // 12: usercenter.v1.CreateSecretRequest
	(*UpdateSecretRequest)(nil),    // 13: usercenter.v1.UpdateSecretRequest
	(*DeleteSecretRequest)(nil),    // 14: usercenter.v1.DeleteSecretRequest
	(*GetSecretRequest)(nil),       // 15: usercenter.v1.GetSecretRequest
	(*ListSecretRequest)(nil),      // 16: usercenter.v1.ListSecretRequest
	(*LoginReply)(nil),             // 17: usercenter.v1.LoginReply
	(*LogoutResponse)(nil),         // 18: usercenter.v1.LogoutResponse
	(*AuthenticateResponse)(nil),   // 19: usercenter.v1.AuthenticateResponse
	(*AuthorizeResponse)(nil),      // 20: usercenter.v1.AuthorizeResponse
	(*AuthResponse)(nil),           // 21: usercenter.v1.AuthResponse
	(*CreateUserResponse)(nil),     // 22: usercenter.v1.CreateUserResponse
	(*UpdateUserResponse)(nil),     // 23: usercenter.v1.UpdateUserResponse
	(*DeleteUserResponse)(nil),     // 24: usercenter.v1.DeleteUserResponse
	(*GetUserResponse)(nil),        // 25: usercenter.v1.GetUserResponse
	(*ListUserResponse)(nil),       // 26: usercenter.v1.ListUserResponse
	(*UpdatePasswordResponse)(nil), // 27: usercenter.v1.UpdatePasswordResponse
	(*CreateSecretResponse)(nil),   // 28: usercenter.v1.CreateSecretResponse
	(*UpdateSecretResponse)(nil),   // 29: usercenter.v1.UpdateSecretResponse
	(*DeleteSecretResponse)(nil),   // 30: usercenter.v1.DeleteSecretResponse
	(*GetSecretResponse)(nil),      // 31: usercenter.v1.GetSecretResponse
	(*ListSecretResponse)(nil),     // 32: usercenter.v1.ListSecretResponse
}
var file_usercenter_v1_usercenter_proto_depIdxs = []int32{
	0,  // 0: usercenter.v1.UserCenter.Login:input_type -> usercenter.v1.LoginRequest
	1,  // 1: usercenter.v1.UserCenter.Logout:input_type -> usercenter.v1.LogoutRequest
	2,  // 2: usercenter.v1.UserCenter.RefreshToken:input_type -> usercenter.v1.RefreshTokenRequest
	3,  // 3: usercenter.v1.UserCenter.Authenticate:input_type -> usercenter.v1.AuthenticateRequest
	4,  // 4: usercenter.v1.UserCenter.Authorize:input_type -> usercenter.v1.AuthorizeRequest
	5,  // 5: usercenter.v1.UserCenter.Auth:input_type -> usercenter.v1.AuthRequest
	6,  // 6: usercenter.v1.UserCenter.CreateUser:input_type -> usercenter.v1.CreateUserRequest
	7,  // 7: usercenter.v1.UserCenter.UpdateUser:input_type -> usercenter.v1.UpdateUserRequest
	8,  // 8: usercenter.v1.UserCenter.DeleteUser:input_type -> usercenter.v1.DeleteUserRequest
	9,  // 9: usercenter.v1.UserCenter.GetUser:input_type -> usercenter.v1.GetUserRequest
	10, // 10: usercenter.v1.UserCenter.ListUser:input_type -> usercenter.v1.ListUserRequest
	11, // 11: usercenter.v1.UserCenter.UpdatePassword:input_type -> usercenter.v1.UpdatePasswordRequest
	12, // 12: usercenter.v1.UserCenter.CreateSecret:input_type -> usercenter.v1.CreateSecretRequest
	13, // 13: usercenter.v1.UserCenter.UpdateSecret:input_type -> usercenter.v1.UpdateSecretRequest
	14, // 14: usercenter.v1.UserCenter.DeleteSecret:input_type -> usercenter.v1.DeleteSecretRequest
	15, // 15: usercenter.v1.UserCenter.GetSecret:input_type -> usercenter.v1.GetSecretRequest
	16, // 16: usercenter.v1.UserCenter.ListSecret:input_type -> usercenter.v1.ListSecretRequest
	17, // 17: usercenter.v1.UserCenter.Login:output_type -> usercenter.v1.LoginReply
	18, // 18: usercenter.v1.UserCenter.Logout:output_type -> usercenter.v1.LogoutResponse
	17, // 19: usercenter.v1.UserCenter.RefreshToken:output_type -> usercenter.v1.LoginReply
	19, // 20: usercenter.v1.UserCenter.Authenticate:output_type -> usercenter.v1.AuthenticateResponse
	20, // 21: usercenter.v1.UserCenter.Authorize:output_type -> usercenter.v1.AuthorizeResponse
	21, // 22: usercenter.v1.UserCenter.Auth:output_type -> usercenter.v1.AuthResponse
	22, // 23: usercenter.v1.UserCenter.CreateUser:output_type -> usercenter.v1.CreateUserResponse
	23, // 24: usercenter.v1.UserCenter.UpdateUser:output_type -> usercenter.v1.UpdateUserResponse
	24, // 25: usercenter.v1.UserCenter.DeleteUser:output_type -> usercenter.v1.DeleteUserResponse
	25, // 26: usercenter.v1.UserCenter.GetUser:output_type -> usercenter.v1.GetUserResponse
	26, // 27: usercenter.v1.UserCenter.ListUser:output_type -> usercenter.v1.ListUserResponse
	27, // 28: usercenter.v1.UserCenter.UpdatePassword:output_type -> usercenter.v1.UpdatePasswordResponse
	28, // 29: usercenter.v1.UserCenter.CreateSecret:output_type -> usercenter.v1.CreateSecretResponse
	29, // 30: usercenter.v1.UserCenter.UpdateSecret:output_type -> usercenter.v1.UpdateSecretResponse
	30, // 31: usercenter.v1.UserCenter.DeleteSecret:output_type -> usercenter.v1.DeleteSecretResponse
	31, // 32: usercenter.v1.UserCenter.GetSecret:output_type -> usercenter.v1.GetSecretResponse
	32, // 33: usercenter.v1.UserCenter.ListSecret:output_type -> usercenter.v1.ListSecretResponse
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_usercenter_v1_usercenter_proto_init() }
func file_usercenter_v1_usercenter_proto_init() {
	if File_usercenter_v1_usercenter_proto != nil {
		return
	}
	file_usercenter_v1_secret_proto_init()
	file_usercenter_v1_user_proto_init()
	file_usercenter_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_usercenter_v1_usercenter_proto_rawDesc), len(file_usercenter_v1_usercenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_usercenter_v1_usercenter_proto_goTypes,
		DependencyIndexes: file_usercenter_v1_usercenter_proto_depIdxs,
	}.Build()
	File_usercenter_v1_usercenter_proto = out.File
	file_usercenter_v1_usercenter_proto_goTypes = nil
	file_usercenter_v1_usercenter_proto_depIdxs = nil
}
