#!/usr/bin/env bash

PROJ_ROOT_DIR=$(dirname "${BASH_SOURCE[0]}")/..
source "${PROJ_ROOT_DIR}/scripts/common.sh"

if [ $# -ne 4 ];then
    minerx::log::error "Usage: gen-service-config.sh SERVICE_NAME ENV_FILE TEMPLATE_FILE OUTPUT_DIR"
    exit 1
fi

export SERVICE_NAME=$1
ENV_FILE=$2
TEMPLATE_FILE=$3
OUTPUT_DIR=$4

if [ ! -d ${OUTPUT_DIR} ];then
  mkdir -p ${OUTPUT_DIR}
fi

if [[ " ${MINERX_ALL_COMPONENTS[*]} " != *" ${SERVICE_NAME} "* ]]; then
  exit 0
fi

function get_apiserver_systemd_file()
{
  cat << EOF
# minerx-apiserver.service generated by scripts/gen-systemd.sh. DO NOT EDIT.
[Unit]
Description=Systemd unit file for minerx-apiserver
Documentation=https://github.com/LiangNing7/minerx/blob/main/manifests/installation/minerx/systemd/README.md

[Service]
WorkingDirectory=${MINERX_INSTALL_DIR}
ExecStartPre=/usr/bin/mkdir -p ${MINERX_DATA_DIR}/minerx-apiserver
ExecStartPre=/usr/bin/mkdir -p ${MINERX_LOG_DIR}
ExecStart=/opt/minerx/bin/minerx-apiserver --bind-address=${MINERX_APISERVER_BIND_ADDRESS} --secure-port ${MINERX_APISERVER_SECURE_PORT} --etcd-servers ${MINERX_APISERVER_ETCD_SERVERS} --client-ca-file=${MINERX_APISERVER_CLIENT_CA_FILE} --tls-cert-file=${MINERX_APISERVER_TLS_CERT_FILE} --tls-private-key-file=${MINERX_APISERVER_TLS_PRIVATE_KEY_FILE} --v=${MINERX_APISERVER_V_LEVEL}
Restart=always
RestartSec=5
StartLimitInterval=0

[Install]
WantedBy=multi-user.target
EOF
}

source ${ENV_FILE}

# Some customized processing
case ${TEMPLATE_FILE} in
  *minerx.systemd.tmpl.service)
    if [ "${SERVICE_NAME}" == "minerx-apiserver" ];then
      get_apiserver_systemd_file > ${OUTPUT_DIR}/${SERVICE_NAME}.service
      exit 0
    fi
    if [ "${SERVICE_NAME}" == "minerxctl" ];then
      exit 0
    fi
    ;;
  *minerx-apiserver.config.tmpl.yaml)
    exit 0
    ;;
  *)
    ;;
esac

suffix=$(echo $TEMPLATE_FILE | awk -F'.' '{print $NF}')
${PROJ_ROOT_DIR}/scripts/gen-config.sh ${ENV_FILE} ${TEMPLATE_FILE} > ${OUTPUT_DIR}/${SERVICE_NAME}.${suffix}

# Fix
if [[ "${TEMPLATE_FILE}" =~ .*minerx.systemd.tmpl.service ]] && [[ "${SERVICE_NAME}" =~ minerx.*controller ]];then
  escaped_minerx_config_dir="$(sed -e 's/[\/&]/\\&/g' <<< "${MINERX_CONFIG_DIR}")"
  sed -i "/ExecStart=/s/$/ --kubeconfig=${escaped_minerx_config_dir}\/config/" ${OUTPUT_DIR}/${SERVICE_NAME}.${suffix}
fi

