// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package gateway

import (
	"github.com/LiangNing7/goutils/pkg/db"
	"github.com/LiangNing7/goutils/pkg/server"
	validation2 "github.com/LiangNing7/goutils/pkg/validation"
	"github.com/LiangNing7/minerx/internal/gateway/biz"
	"github.com/LiangNing7/minerx/internal/gateway/handler"
	"github.com/LiangNing7/minerx/internal/gateway/pkg/validation"
	"github.com/LiangNing7/minerx/internal/gateway/store"
	"github.com/LiangNing7/minerx/internal/pkg/client/usercenter"
	"github.com/LiangNing7/minerx/internal/pkg/idempotent"
	"github.com/LiangNing7/minerx/pkg/generated/clientset/versioned"
)

// Injectors from wire.go:

func InitializeWebServer(arg <-chan struct{}, config *Config, versionedInterface versioned.Interface, mySQLOptions *db.MySQLOptions, redisOptions *db.RedisOptions) (server.Server, error) {
	etcdOptions := config.EtcdOptions
	registrar := server.NewEtcdRegistrar(etcdOptions)
	kratosAppConfig := ProvideKratosAppConfig(registrar)
	gormDB, err := db.NewMySQL(mySQLOptions)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(gormDB)
	sharedInformerFactory, err := createInformers(arg, versionedInterface)
	if err != nil {
		return nil, err
	}
	bizBiz := biz.NewBiz(datastore, versionedInterface, sharedInformerFactory)
	client, err := db.NewRedis(redisOptions)
	if err != nil {
		return nil, err
	}
	idempotentIdempotent, err := idempotent.NewIdempotent(client)
	if err != nil {
		return nil, err
	}
	handlerHandler := handler.NewHandler(bizBiz, idempotentIdempotent)
	logger := ProvideKratosLogger()
	userCenterOptions := config.UserCenterOptions
	impl := usercenter.NewUserCenter(userCenterOptions, etcdOptions)
	validator := validation.New(datastore)
	validationValidator := validation2.NewValidator(validator)
	v := NewMiddlewares(logger, idempotentIdempotent, impl, validationValidator)
	serverConfig := &ServerConfig{
		cfg:         config,
		appConfig:   kratosAppConfig,
		handler:     handlerHandler,
		middlewares: v,
	}
	serverServer, err := NewWebServer(serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
