package app

import (
	"fmt"

	"github.com/LiangNing7/goutils/pkg/app"
	utilruntime "k8s.io/apimachinery/pkg/util/runtime"
	genericapiserver "k8s.io/apiserver/pkg/server"
	utilfeature "k8s.io/apiserver/pkg/util/feature"
	logsapi "k8s.io/component-base/logs/api/v1"

	"github.com/LiangNing7/minerx/cmd/minerx-pump/app/options"
)

func init() {
	utilruntime.Must(logsapi.AddFeatureGates(utilfeature.DefaultMutableFeatureGate))
}

const commandDesc = `Pump is a pluggable analytics purger to move Analytics generated by your minerx nodes to any back-end.

Find more minerx-pump information at:
    https://github.com/LiangNing7/minerx/blob/master/docs/guide/en-US/cmd/minerx-pump.md`

// NewApp creates and returns a new App object with default parameters.
func NewApp() *app.App {
	opts := options.NewServerOptions()
	application := app.NewApp(
		"minerx-pump",
		"Launch a minerx pump server",
		app.WithDescription(commandDesc),
		app.WithOptions(opts),
		app.WithDefaultValidArgs(),
		app.WithRunFunc(run(opts)),
		app.WithHealthCheckFunc(func() error {
			go opts.HealthOptions.ServeHealthCheck()
			return nil
		}),
	)

	return application
}

// run contains the main logic for initializing and running the server.
func run(opts *options.ServerOptions) app.RunFunc {
	return func() error {
		// Load the configuration options
		cfg, err := opts.Config()
		if err != nil {
			return fmt.Errorf("failed to load configuration: %w", err)
		}

		ctx := genericapiserver.SetupSignalContext()

		// Build the server using the configuration
		server, err := cfg.NewServer(ctx)
		if err != nil {
			return fmt.Errorf("failed to create server: %w", err)
		}

		// Run the server with signal context for graceful shutdown
		return server.Run(ctx)
	}
}
