// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cacheserver

import (
	"github.com/LiangNing7/goutils/pkg/db"
	"github.com/LiangNing7/goutils/pkg/server"
	"github.com/LiangNing7/minerx/internal/cacheserver/biz"
	"github.com/LiangNing7/minerx/internal/cacheserver/handler"
	"github.com/LiangNing7/minerx/internal/cacheserver/store"
	"github.com/LiangNing7/minerx/pkg/cache"
	"google.golang.org/protobuf/types/known/anypb"
)

// Injectors from wire.go:

func InitializeWebServer(config *Config, mySQLOptions *db.MySQLOptions, cacheCache cache.Cache[*anypb.Any], bool2 bool) (server.Server, error) {
	gormDB, err := db.NewMySQL(mySQLOptions)
	if err != nil {
		return nil, err
	}
	datastore := store.NewStore(gormDB, bool2)
	bizBiz := biz.NewBiz(cacheCache, datastore)
	handlerHandler := handler.NewHandler(bizBiz)
	serverConfig := &ServerConfig{
		cfg:     config,
		handler: handlerHandler,
	}
	serverServer, err := NewWebServer(serverConfig)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}
