// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: nightwatch/v1/cronjob.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConcurrencyPolicy 描述了作业的处理方式。只能指定以下并发策略中的一个。
// 如果未指定以下任何策略，则默认策略为 ForbidConcurrent
type ConcurrencyPolicy int32

const (
	// ForbidConcurrent 禁止并发运行，如果先前的作业尚未完成，则跳过下一个运行。
	ConcurrencyPolicy_ForbidConcurrent ConcurrencyPolicy = 0
	// AllowConcurrent 允许 CronJobs 并发运行。
	ConcurrencyPolicy_AllowConcurrent ConcurrencyPolicy = 1
	// ReplaceConcurrent 取消当前正在运行的作业，并用一个新的作业替代它。
	ConcurrencyPolicy_ReplaceConcurren ConcurrencyPolicy = 2
)

// Enum value maps for ConcurrencyPolicy.
var (
	ConcurrencyPolicy_name = map[int32]string{
		0: "ForbidConcurrent",
		1: "AllowConcurrent",
		2: "ReplaceConcurren",
	}
	ConcurrencyPolicy_value = map[string]int32{
		"ForbidConcurrent": 0,
		"AllowConcurrent":  1,
		"ReplaceConcurren": 2,
	}
)

func (x ConcurrencyPolicy) Enum() *ConcurrencyPolicy {
	p := new(ConcurrencyPolicy)
	*p = x
	return p
}

func (x ConcurrencyPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConcurrencyPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_nightwatch_v1_cronjob_proto_enumTypes[0].Descriptor()
}

func (ConcurrencyPolicy) Type() protoreflect.EnumType {
	return &file_nightwatch_v1_cronjob_proto_enumTypes[0]
}

func (x ConcurrencyPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConcurrencyPolicy.Descriptor instead.
func (ConcurrencyPolicy) EnumDescriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{0}
}

// CronJob 表示单个 Cron 作业的配置。
type CronJob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CronJob 名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// CronJob ID
	CronJobID string `protobuf:"bytes,2,opt,name=cronJobID,proto3" json:"cronJobID,omitempty"`
	// 创建人
	UserID string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	// CronJob 作用域
	Scope string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	// CronJob 描述
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Quartz 格式的调度时间描述。http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/tutorial-lesson-06.html
	Schedule string `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	// CronJob 任务状态，例如：{"active":[1,2],"lastScheduleTime":1234,"lastSuccessfulTime":1234, "lastJobID": 1234}
	Status *CronJobStatus `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	// 作业处理方式（1 串行，2 并行，3 替换，默认 1）
	ConcurrencyPolicy ConcurrencyPolicy `protobuf:"varint,8,opt,name=concurrencyPolicy,proto3,enum=nightwatch.v1.ConcurrencyPolicy" json:"concurrencyPolicy,omitempty"`
	// 是否挂起（1 挂起，0 不挂起, 默认 0）
	Suspend int32 `protobuf:"varint,9,opt,name=suspend,proto3" json:"suspend,omitempty"`
	// Job 模版
	JobTemplate *Job `protobuf:"bytes,10,opt,name=jobTemplate,proto3" json:"jobTemplate,omitempty"`
	// 要保留的成功完成作业的数量。值必须是非负整数。默认值为 10。
	SuccessHistoryLimit int32 `protobuf:"varint,11,opt,name=successHistoryLimit,proto3" json:"successHistoryLimit,omitempty"`
	// 要保留的失败完成作业的数量。值必须是非负整数。  默认值为 5。
	FailedHistoryLimit int32 `protobuf:"varint,12,opt,name=failedHistoryLimit,proto3" json:"failedHistoryLimit,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// 更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CronJob) Reset() {
	*x = CronJob{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJob) ProtoMessage() {}

func (x *CronJob) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJob.ProtoReflect.Descriptor instead.
func (*CronJob) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{0}
}

func (x *CronJob) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CronJob) GetCronJobID() string {
	if x != nil {
		return x.CronJobID
	}
	return ""
}

func (x *CronJob) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *CronJob) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CronJob) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CronJob) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CronJob) GetStatus() *CronJobStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CronJob) GetConcurrencyPolicy() ConcurrencyPolicy {
	if x != nil {
		return x.ConcurrencyPolicy
	}
	return ConcurrencyPolicy_ForbidConcurrent
}

func (x *CronJob) GetSuspend() int32 {
	if x != nil {
		return x.Suspend
	}
	return 0
}

func (x *CronJob) GetJobTemplate() *Job {
	if x != nil {
		return x.JobTemplate
	}
	return nil
}

func (x *CronJob) GetSuccessHistoryLimit() int32 {
	if x != nil {
		return x.SuccessHistoryLimit
	}
	return 0
}

func (x *CronJob) GetFailedHistoryLimit() int32 {
	if x != nil {
		return x.FailedHistoryLimit
	}
	return 0
}

func (x *CronJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *CronJob) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CronJobStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Active             []int64                `protobuf:"varint,1,rep,packed,name=active,proto3" json:"active,omitempty"`
	LastScheduleTime   int64                  `protobuf:"varint,2,opt,name=lastScheduleTime,proto3" json:"lastScheduleTime,omitempty"`
	LastSuccessfulTime int64                  `protobuf:"varint,3,opt,name=lastSuccessfulTime,proto3" json:"lastSuccessfulTime,omitempty"`
	LastJobID          string                 `protobuf:"bytes,4,opt,name=lastJobID,proto3" json:"lastJobID,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CronJobStatus) Reset() {
	*x = CronJobStatus{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CronJobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CronJobStatus) ProtoMessage() {}

func (x *CronJobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CronJobStatus.ProtoReflect.Descriptor instead.
func (*CronJobStatus) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{1}
}

func (x *CronJobStatus) GetActive() []int64 {
	if x != nil {
		return x.Active
	}
	return nil
}

func (x *CronJobStatus) GetLastScheduleTime() int64 {
	if x != nil {
		return x.LastScheduleTime
	}
	return 0
}

func (x *CronJobStatus) GetLastSuccessfulTime() int64 {
	if x != nil {
		return x.LastSuccessfulTime
	}
	return 0
}

func (x *CronJobStatus) GetLastJobID() string {
	if x != nil {
		return x.LastJobID
	}
	return ""
}

type CreateCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJob       *CronJob               `protobuf:"bytes,1,opt,name=cronJob,proto3" json:"cronJob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCronJobRequest) Reset() {
	*x = CreateCronJobRequest{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCronJobRequest) ProtoMessage() {}

func (x *CreateCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCronJobRequest.ProtoReflect.Descriptor instead.
func (*CreateCronJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCronJobRequest) GetCronJob() *CronJob {
	if x != nil {
		return x.CronJob
	}
	return nil
}

type CreateCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJobID     string                 `protobuf:"bytes,1,opt,name=cronJobID,proto3" json:"cronJobID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCronJobResponse) Reset() {
	*x = CreateCronJobResponse{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCronJobResponse) ProtoMessage() {}

func (x *CreateCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCronJobResponse.ProtoReflect.Descriptor instead.
func (*CreateCronJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCronJobResponse) GetCronJobID() string {
	if x != nil {
		return x.CronJobID
	}
	return ""
}

type UpdateCronJobRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CronJobID           string                 `protobuf:"bytes,1,opt,name=cronJobID,proto3" json:"cronJobID,omitempty"`
	Name                *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description         *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Schedule            *string                `protobuf:"bytes,6,opt,name=schedule,proto3,oneof" json:"schedule,omitempty"`
	ConcurrencyPolicy   *ConcurrencyPolicy     `protobuf:"varint,8,opt,name=concurrencyPolicy,proto3,enum=nightwatch.v1.ConcurrencyPolicy,oneof" json:"concurrencyPolicy,omitempty"`
	Suspend             *int32                 `protobuf:"varint,9,opt,name=suspend,proto3,oneof" json:"suspend,omitempty"`
	SuccessHistoryLimit *int32                 `protobuf:"varint,11,opt,name=successHistoryLimit,proto3,oneof" json:"successHistoryLimit,omitempty"`
	FailedHistoryLimit  *int32                 `protobuf:"varint,12,opt,name=failedHistoryLimit,proto3,oneof" json:"failedHistoryLimit,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateCronJobRequest) Reset() {
	*x = UpdateCronJobRequest{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronJobRequest) ProtoMessage() {}

func (x *UpdateCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateCronJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCronJobRequest) GetCronJobID() string {
	if x != nil {
		return x.CronJobID
	}
	return ""
}

func (x *UpdateCronJobRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCronJobRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCronJobRequest) GetSchedule() string {
	if x != nil && x.Schedule != nil {
		return *x.Schedule
	}
	return ""
}

func (x *UpdateCronJobRequest) GetConcurrencyPolicy() ConcurrencyPolicy {
	if x != nil && x.ConcurrencyPolicy != nil {
		return *x.ConcurrencyPolicy
	}
	return ConcurrencyPolicy_ForbidConcurrent
}

func (x *UpdateCronJobRequest) GetSuspend() int32 {
	if x != nil && x.Suspend != nil {
		return *x.Suspend
	}
	return 0
}

func (x *UpdateCronJobRequest) GetSuccessHistoryLimit() int32 {
	if x != nil && x.SuccessHistoryLimit != nil {
		return *x.SuccessHistoryLimit
	}
	return 0
}

func (x *UpdateCronJobRequest) GetFailedHistoryLimit() int32 {
	if x != nil && x.FailedHistoryLimit != nil {
		return *x.FailedHistoryLimit
	}
	return 0
}

type UpdateCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCronJobResponse) Reset() {
	*x = UpdateCronJobResponse{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCronJobResponse) ProtoMessage() {}

func (x *UpdateCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCronJobResponse.ProtoReflect.Descriptor instead.
func (*UpdateCronJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{5}
}

type DeleteCronJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJobIDs    []string               `protobuf:"bytes,1,rep,name=cronJobIDs,proto3" json:"cronJobIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronJobRequest) Reset() {
	*x = DeleteCronJobRequest{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronJobRequest) ProtoMessage() {}

func (x *DeleteCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteCronJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCronJobRequest) GetCronJobIDs() []string {
	if x != nil {
		return x.CronJobIDs
	}
	return nil
}

type DeleteCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCronJobResponse) Reset() {
	*x = DeleteCronJobResponse{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCronJobResponse) ProtoMessage() {}

func (x *DeleteCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCronJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteCronJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{7}
}

type GetCronJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"cronJobID"
	CronJobID     string `protobuf:"bytes,1,opt,name=cronJobID,proto3" json:"cronJobID,omitempty" uri:"cronJobID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronJobRequest) Reset() {
	*x = GetCronJobRequest{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronJobRequest) ProtoMessage() {}

func (x *GetCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronJobRequest.ProtoReflect.Descriptor instead.
func (*GetCronJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{8}
}

func (x *GetCronJobRequest) GetCronJobID() string {
	if x != nil {
		return x.CronJobID
	}
	return ""
}

type GetCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CronJob       *CronJob               `protobuf:"bytes,1,opt,name=cronJob,proto3" json:"cronJob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCronJobResponse) Reset() {
	*x = GetCronJobResponse{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCronJobResponse) ProtoMessage() {}

func (x *GetCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCronJobResponse.ProtoReflect.Descriptor instead.
func (*GetCronJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{9}
}

func (x *GetCronJobResponse) GetCronJob() *CronJob {
	if x != nil {
		return x.CronJob
	}
	return nil
}

type ListCronJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"offset"
	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// @gotags: form:"limit"
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobRequest) Reset() {
	*x = ListCronJobRequest{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobRequest) ProtoMessage() {}

func (x *ListCronJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobRequest.ProtoReflect.Descriptor instead.
func (*ListCronJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{10}
}

func (x *ListCronJobRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCronJobRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListCronJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	CronJobs      []*CronJob             `protobuf:"bytes,2,rep,name=cronJobs,proto3" json:"cronJobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCronJobResponse) Reset() {
	*x = ListCronJobResponse{}
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCronJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCronJobResponse) ProtoMessage() {}

func (x *ListCronJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_cronjob_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCronJobResponse.ProtoReflect.Descriptor instead.
func (*ListCronJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_cronjob_proto_rawDescGZIP(), []int{11}
}

func (x *ListCronJobResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCronJobResponse) GetCronJobs() []*CronJob {
	if x != nil {
		return x.CronJobs
	}
	return nil
}

var File_nightwatch_v1_cronjob_proto protoreflect.FileDescriptor

const file_nightwatch_v1_cronjob_proto_rawDesc = "" +
	"\n" +
	"\x1bnightwatch/v1/cronjob.proto\x12\rnightwatch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17nightwatch/v1/job.proto\"\xd3\x04\n" +
	"\aCronJob\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcronJobID\x18\x02 \x01(\tR\tcronJobID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\tR\x06userID\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\tR\bschedule\x124\n" +
	"\x06status\x18\a \x01(\v2\x1c.nightwatch.v1.CronJobStatusR\x06status\x12N\n" +
	"\x11concurrencyPolicy\x18\b \x01(\x0e2 .nightwatch.v1.ConcurrencyPolicyR\x11concurrencyPolicy\x12\x18\n" +
	"\asuspend\x18\t \x01(\x05R\asuspend\x124\n" +
	"\vjobTemplate\x18\n" +
	" \x01(\v2\x12.nightwatch.v1.JobR\vjobTemplate\x120\n" +
	"\x13successHistoryLimit\x18\v \x01(\x05R\x13successHistoryLimit\x12.\n" +
	"\x12failedHistoryLimit\x18\f \x01(\x05R\x12failedHistoryLimit\x128\n" +
	"\tcreatedAt\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa1\x01\n" +
	"\rCronJobStatus\x12\x16\n" +
	"\x06active\x18\x01 \x03(\x03R\x06active\x12*\n" +
	"\x10lastScheduleTime\x18\x02 \x01(\x03R\x10lastScheduleTime\x12.\n" +
	"\x12lastSuccessfulTime\x18\x03 \x01(\x03R\x12lastSuccessfulTime\x12\x1c\n" +
	"\tlastJobID\x18\x04 \x01(\tR\tlastJobID\"H\n" +
	"\x14CreateCronJobRequest\x120\n" +
	"\acronJob\x18\x01 \x01(\v2\x16.nightwatch.v1.CronJobR\acronJob\"5\n" +
	"\x15CreateCronJobResponse\x12\x1c\n" +
	"\tcronJobID\x18\x01 \x01(\tR\tcronJobID\"\xec\x03\n" +
	"\x14UpdateCronJobRequest\x12\x1c\n" +
	"\tcronJobID\x18\x01 \x01(\tR\tcronJobID\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1f\n" +
	"\bschedule\x18\x06 \x01(\tH\x02R\bschedule\x88\x01\x01\x12S\n" +
	"\x11concurrencyPolicy\x18\b \x01(\x0e2 .nightwatch.v1.ConcurrencyPolicyH\x03R\x11concurrencyPolicy\x88\x01\x01\x12\x1d\n" +
	"\asuspend\x18\t \x01(\x05H\x04R\asuspend\x88\x01\x01\x125\n" +
	"\x13successHistoryLimit\x18\v \x01(\x05H\x05R\x13successHistoryLimit\x88\x01\x01\x123\n" +
	"\x12failedHistoryLimit\x18\f \x01(\x05H\x06R\x12failedHistoryLimit\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_scheduleB\x14\n" +
	"\x12_concurrencyPolicyB\n" +
	"\n" +
	"\b_suspendB\x16\n" +
	"\x14_successHistoryLimitB\x15\n" +
	"\x13_failedHistoryLimit\"\x17\n" +
	"\x15UpdateCronJobResponse\"6\n" +
	"\x14DeleteCronJobRequest\x12\x1e\n" +
	"\n" +
	"cronJobIDs\x18\x01 \x03(\tR\n" +
	"cronJobIDs\"\x17\n" +
	"\x15DeleteCronJobResponse\"1\n" +
	"\x11GetCronJobRequest\x12\x1c\n" +
	"\tcronJobID\x18\x01 \x01(\tR\tcronJobID\"F\n" +
	"\x12GetCronJobResponse\x120\n" +
	"\acronJob\x18\x01 \x01(\v2\x16.nightwatch.v1.CronJobR\acronJob\"B\n" +
	"\x12ListCronJobRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"_\n" +
	"\x13ListCronJobResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x122\n" +
	"\bcronJobs\x18\x02 \x03(\v2\x16.nightwatch.v1.CronJobR\bcronJobs*T\n" +
	"\x11ConcurrencyPolicy\x12\x14\n" +
	"\x10ForbidConcurrent\x10\x00\x12\x13\n" +
	"\x0fAllowConcurrent\x10\x01\x12\x14\n" +
	"\x10ReplaceConcurren\x10\x02B7Z5github.com/LiangNing7/minerx/pkg/api/nightwatch/v1;v1b\x06proto3"

var (
	file_nightwatch_v1_cronjob_proto_rawDescOnce sync.Once
	file_nightwatch_v1_cronjob_proto_rawDescData []byte
)

func file_nightwatch_v1_cronjob_proto_rawDescGZIP() []byte {
	file_nightwatch_v1_cronjob_proto_rawDescOnce.Do(func() {
		file_nightwatch_v1_cronjob_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nightwatch_v1_cronjob_proto_rawDesc), len(file_nightwatch_v1_cronjob_proto_rawDesc)))
	})
	return file_nightwatch_v1_cronjob_proto_rawDescData
}

var file_nightwatch_v1_cronjob_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nightwatch_v1_cronjob_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_nightwatch_v1_cronjob_proto_goTypes = []any{
	(ConcurrencyPolicy)(0),        // 0: nightwatch.v1.ConcurrencyPolicy
	(*CronJob)(nil),               // 1: nightwatch.v1.CronJob
	(*CronJobStatus)(nil),         // 2: nightwatch.v1.CronJobStatus
	(*CreateCronJobRequest)(nil),  // 3: nightwatch.v1.CreateCronJobRequest
	(*CreateCronJobResponse)(nil), // 4: nightwatch.v1.CreateCronJobResponse
	(*UpdateCronJobRequest)(nil),  // 5: nightwatch.v1.UpdateCronJobRequest
	(*UpdateCronJobResponse)(nil), // 6: nightwatch.v1.UpdateCronJobResponse
	(*DeleteCronJobRequest)(nil),  // 7: nightwatch.v1.DeleteCronJobRequest
	(*DeleteCronJobResponse)(nil), // 8: nightwatch.v1.DeleteCronJobResponse
	(*GetCronJobRequest)(nil),     // 9: nightwatch.v1.GetCronJobRequest
	(*GetCronJobResponse)(nil),    // 10: nightwatch.v1.GetCronJobResponse
	(*ListCronJobRequest)(nil),    // 11: nightwatch.v1.ListCronJobRequest
	(*ListCronJobResponse)(nil),   // 12: nightwatch.v1.ListCronJobResponse
	(*Job)(nil),                   // 13: nightwatch.v1.Job
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_nightwatch_v1_cronjob_proto_depIdxs = []int32{
	2,  // 0: nightwatch.v1.CronJob.status:type_name -> nightwatch.v1.CronJobStatus
	0,  // 1: nightwatch.v1.CronJob.concurrencyPolicy:type_name -> nightwatch.v1.ConcurrencyPolicy
	13, // 2: nightwatch.v1.CronJob.jobTemplate:type_name -> nightwatch.v1.Job
	14, // 3: nightwatch.v1.CronJob.createdAt:type_name -> google.protobuf.Timestamp
	14, // 4: nightwatch.v1.CronJob.updatedAt:type_name -> google.protobuf.Timestamp
	1,  // 5: nightwatch.v1.CreateCronJobRequest.cronJob:type_name -> nightwatch.v1.CronJob
	0,  // 6: nightwatch.v1.UpdateCronJobRequest.concurrencyPolicy:type_name -> nightwatch.v1.ConcurrencyPolicy
	1,  // 7: nightwatch.v1.GetCronJobResponse.cronJob:type_name -> nightwatch.v1.CronJob
	1,  // 8: nightwatch.v1.ListCronJobResponse.cronJobs:type_name -> nightwatch.v1.CronJob
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_nightwatch_v1_cronjob_proto_init() }
func file_nightwatch_v1_cronjob_proto_init() {
	if File_nightwatch_v1_cronjob_proto != nil {
		return
	}
	file_nightwatch_v1_job_proto_init()
	file_nightwatch_v1_cronjob_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nightwatch_v1_cronjob_proto_rawDesc), len(file_nightwatch_v1_cronjob_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nightwatch_v1_cronjob_proto_goTypes,
		DependencyIndexes: file_nightwatch_v1_cronjob_proto_depIdxs,
		EnumInfos:         file_nightwatch_v1_cronjob_proto_enumTypes,
		MessageInfos:      file_nightwatch_v1_cronjob_proto_msgTypes,
	}.Build()
	File_nightwatch_v1_cronjob_proto = out.File
	file_nightwatch_v1_cronjob_proto_goTypes = nil
	file_nightwatch_v1_cronjob_proto_depIdxs = nil
}
