// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: nightwatch/v1/job.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Job 名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Job ID
	JobID string `protobuf:"bytes,2,opt,name=jobID,proto3" json:"jobID,omitempty"`
	// 创建人
	UserID string `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	// CronJob ID
	CronJobID string `protobuf:"bytes,4,opt,name=cronJobID,proto3" json:"cronJobID,omitempty"`
	// Job 作用域
	Scope string `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	// Job 描述
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Watcher     string `protobuf:"bytes,7,opt,name=watcher,proto3" json:"watcher,omitempty"`
	// Job 参数
	Params *JobParams `protobuf:"bytes,8,opt,name=params,proto3" json:"params,omitempty"`
	// Job 执行结果
	Results *JobResults `protobuf:"bytes,9,opt,name=results,proto3" json:"results,omitempty"`
	// Job 状态：Pending、Running、Succeeded、Failed
	Status string `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	// Job 状态：Pending、Running、Succeeded、Failed
	Conditions []*JobCondition `protobuf:"bytes,11,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// Job 开始时间
	StartedAt int64 `protobuf:"varint,12,opt,name=startedAt,proto3" json:"startedAt,omitempty"`
	// Job 结束时间
	EndedAt int64 `protobuf:"varint,13,opt,name=endedAt,proto3" json:"endedAt,omitempty"`
	// 创建时间
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	// 更新时间
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *Job) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *Job) GetCronJobID() string {
	if x != nil {
		return x.CronJobID
	}
	return ""
}

func (x *Job) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Job) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Job) GetWatcher() string {
	if x != nil {
		return x.Watcher
	}
	return ""
}

func (x *Job) GetParams() *JobParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Job) GetResults() *JobResults {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetConditions() []*JobCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Job) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Job) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

func (x *Job) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Job) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type JobParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Train         *TrainParams           `protobuf:"bytes,1,opt,name=train,proto3" json:"train,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobParams) Reset() {
	*x = JobParams{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobParams) ProtoMessage() {}

func (x *JobParams) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobParams.ProtoReflect.Descriptor instead.
func (*JobParams) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobParams) GetTrain() *TrainParams {
	if x != nil {
		return x.Train
	}
	return nil
}

type TrainParams struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IdempotentExecution int64                  `protobuf:"varint,1,opt,name=idempotentExecution,proto3" json:"idempotentExecution,omitempty"`
	JobTimeout          int64                  `protobuf:"varint,2,opt,name=jobTimeout,proto3" json:"jobTimeout,omitempty"`
	BatchSize           int64                  `protobuf:"varint,3,opt,name=batchSize,proto3" json:"batchSize,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TrainParams) Reset() {
	*x = TrainParams{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainParams) ProtoMessage() {}

func (x *TrainParams) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainParams.ProtoReflect.Descriptor instead.
func (*TrainParams) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *TrainParams) GetIdempotentExecution() int64 {
	if x != nil {
		return x.IdempotentExecution
	}
	return 0
}

func (x *TrainParams) GetJobTimeout() int64 {
	if x != nil {
		return x.JobTimeout
	}
	return 0
}

func (x *TrainParams) GetBatchSize() int64 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type JobResults struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Train         *TrainResults          `protobuf:"bytes,1,opt,name=train,proto3" json:"train,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResults) Reset() {
	*x = JobResults{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResults) ProtoMessage() {}

func (x *JobResults) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResults.ProtoReflect.Descriptor instead.
func (*JobResults) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *JobResults) GetTrain() *TrainResults {
	if x != nil {
		return x.Train
	}
	return nil
}

type TrainResults struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EmbeddedDataPath *string                `protobuf:"bytes,1,opt,name=embeddedDataPath,proto3,oneof" json:"embeddedDataPath,omitempty"`
	TaskID           *string                `protobuf:"bytes,2,opt,name=taskID,proto3,oneof" json:"taskID,omitempty"`
	DataPath         *string                `protobuf:"bytes,4,opt,name=dataPath,proto3,oneof" json:"dataPath,omitempty"`
	ResultPath       *string                `protobuf:"bytes,3,opt,name=resultPath,proto3,oneof" json:"resultPath,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TrainResults) Reset() {
	*x = TrainResults{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResults) ProtoMessage() {}

func (x *TrainResults) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResults.ProtoReflect.Descriptor instead.
func (*TrainResults) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{4}
}

func (x *TrainResults) GetEmbeddedDataPath() string {
	if x != nil && x.EmbeddedDataPath != nil {
		return *x.EmbeddedDataPath
	}
	return ""
}

func (x *TrainResults) GetTaskID() string {
	if x != nil && x.TaskID != nil {
		return *x.TaskID
	}
	return ""
}

func (x *TrainResults) GetDataPath() string {
	if x != nil && x.DataPath != nil {
		return *x.DataPath
	}
	return ""
}

func (x *TrainResults) GetResultPath() string {
	if x != nil && x.ResultPath != nil {
		return *x.ResultPath
	}
	return ""
}

type JobCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of the condition (e.g., "Downloaed", "Embedded", "Evaluated")
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Status of the condition (True, False, Unknown)
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Message provides additional information when the condition is false
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Last time the condition transitioned from one status to another.
	LastTransitionTime string `protobuf:"bytes,4,opt,name=lastTransitionTime,proto3" json:"lastTransitionTime,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobCondition) Reset() {
	*x = JobCondition{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobCondition) ProtoMessage() {}

func (x *JobCondition) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobCondition.ProtoReflect.Descriptor instead.
func (*JobCondition) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{5}
}

func (x *JobCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobCondition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobCondition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobCondition) GetLastTransitionTime() string {
	if x != nil {
		return x.LastTransitionTime
	}
	return ""
}

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{6}
}

func (x *CreateJobRequest) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type CreateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobID         string                 `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobResponse) Reset() {
	*x = CreateJobResponse{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobResponse) ProtoMessage() {}

func (x *CreateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobResponse.ProtoReflect.Descriptor instead.
func (*CreateJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{7}
}

func (x *CreateJobResponse) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

type UpdateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobID         string                 `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Params        *JobParams             `protobuf:"bytes,4,opt,name=params,proto3,oneof" json:"params,omitempty"`
	Results       *JobResults            `protobuf:"bytes,5,opt,name=results,proto3,oneof" json:"results,omitempty"`
	Status        *string                `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateJobRequest) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

func (x *UpdateJobRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateJobRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateJobRequest) GetParams() *JobParams {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *UpdateJobRequest) GetResults() *JobResults {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *UpdateJobRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type UpdateJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobResponse) Reset() {
	*x = UpdateJobResponse{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobResponse) ProtoMessage() {}

func (x *UpdateJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobResponse.ProtoReflect.Descriptor instead.
func (*UpdateJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{9}
}

type DeleteJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobIDs        []string               `protobuf:"bytes,1,rep,name=jobIDs,proto3" json:"jobIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobRequest) Reset() {
	*x = DeleteJobRequest{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobRequest) ProtoMessage() {}

func (x *DeleteJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobRequest.ProtoReflect.Descriptor instead.
func (*DeleteJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteJobRequest) GetJobIDs() []string {
	if x != nil {
		return x.JobIDs
	}
	return nil
}

type DeleteJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteJobResponse) Reset() {
	*x = DeleteJobResponse{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteJobResponse) ProtoMessage() {}

func (x *DeleteJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteJobResponse.ProtoReflect.Descriptor instead.
func (*DeleteJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{11}
}

type GetJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: uri:"jobID"
	JobID         string `protobuf:"bytes,1,opt,name=jobID,proto3" json:"jobID,omitempty" uri:"jobID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{12}
}

func (x *GetJobRequest) GetJobID() string {
	if x != nil {
		return x.JobID
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *Job                   `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{13}
}

func (x *GetJobResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListJobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: form:"offset"
	Offset int32 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty" form:"offset"`
	// @gotags: form:"limit"
	Limit         int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty" form:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobRequest) Reset() {
	*x = ListJobRequest{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobRequest) ProtoMessage() {}

func (x *ListJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobRequest.ProtoReflect.Descriptor instead.
func (*ListJobRequest) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{14}
}

func (x *ListJobRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListJobRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Jobs          []*Job                 `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobResponse) Reset() {
	*x = ListJobResponse{}
	mi := &file_nightwatch_v1_job_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobResponse) ProtoMessage() {}

func (x *ListJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nightwatch_v1_job_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobResponse.ProtoReflect.Descriptor instead.
func (*ListJobResponse) Descriptor() ([]byte, []int) {
	return file_nightwatch_v1_job_proto_rawDescGZIP(), []int{15}
}

func (x *ListJobResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListJobResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

var File_nightwatch_v1_job_proto protoreflect.FileDescriptor

const file_nightwatch_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x17nightwatch/v1/job.proto\x12\rnightwatch.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x04\n" +
	"\x03Job\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05jobID\x18\x02 \x01(\tR\x05jobID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\tR\x06userID\x12\x1c\n" +
	"\tcronJobID\x18\x04 \x01(\tR\tcronJobID\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x18\n" +
	"\awatcher\x18\a \x01(\tR\awatcher\x120\n" +
	"\x06params\x18\b \x01(\v2\x18.nightwatch.v1.JobParamsR\x06params\x123\n" +
	"\aresults\x18\t \x01(\v2\x19.nightwatch.v1.JobResultsR\aresults\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12;\n" +
	"\n" +
	"conditions\x18\v \x03(\v2\x1b.nightwatch.v1.JobConditionR\n" +
	"conditions\x12\x1c\n" +
	"\tstartedAt\x18\f \x01(\x03R\tstartedAt\x12\x18\n" +
	"\aendedAt\x18\r \x01(\x03R\aendedAt\x128\n" +
	"\tcreatedAt\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"=\n" +
	"\tJobParams\x120\n" +
	"\x05train\x18\x01 \x01(\v2\x1a.nightwatch.v1.TrainParamsR\x05train\"}\n" +
	"\vTrainParams\x120\n" +
	"\x13idempotentExecution\x18\x01 \x01(\x03R\x13idempotentExecution\x12\x1e\n" +
	"\n" +
	"jobTimeout\x18\x02 \x01(\x03R\n" +
	"jobTimeout\x12\x1c\n" +
	"\tbatchSize\x18\x03 \x01(\x03R\tbatchSize\"?\n" +
	"\n" +
	"JobResults\x121\n" +
	"\x05train\x18\x01 \x01(\v2\x1b.nightwatch.v1.TrainResultsR\x05train\"\xde\x01\n" +
	"\fTrainResults\x12/\n" +
	"\x10embeddedDataPath\x18\x01 \x01(\tH\x00R\x10embeddedDataPath\x88\x01\x01\x12\x1b\n" +
	"\x06taskID\x18\x02 \x01(\tH\x01R\x06taskID\x88\x01\x01\x12\x1f\n" +
	"\bdataPath\x18\x04 \x01(\tH\x02R\bdataPath\x88\x01\x01\x12#\n" +
	"\n" +
	"resultPath\x18\x03 \x01(\tH\x03R\n" +
	"resultPath\x88\x01\x01B\x13\n" +
	"\x11_embeddedDataPathB\t\n" +
	"\a_taskIDB\v\n" +
	"\t_dataPathB\r\n" +
	"\v_resultPath\"\x84\x01\n" +
	"\fJobCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\x12lastTransitionTime\x18\x04 \x01(\tR\x12lastTransitionTime\"8\n" +
	"\x10CreateJobRequest\x12$\n" +
	"\x03job\x18\x01 \x01(\v2\x12.nightwatch.v1.JobR\x03job\")\n" +
	"\x11CreateJobResponse\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\"\xb1\x02\n" +
	"\x10UpdateJobRequest\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x125\n" +
	"\x06params\x18\x04 \x01(\v2\x18.nightwatch.v1.JobParamsH\x02R\x06params\x88\x01\x01\x128\n" +
	"\aresults\x18\x05 \x01(\v2\x19.nightwatch.v1.JobResultsH\x03R\aresults\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x04R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_paramsB\n" +
	"\n" +
	"\b_resultsB\t\n" +
	"\a_status\"\x13\n" +
	"\x11UpdateJobResponse\"*\n" +
	"\x10DeleteJobRequest\x12\x16\n" +
	"\x06jobIDs\x18\x01 \x03(\tR\x06jobIDs\"\x13\n" +
	"\x11DeleteJobResponse\"%\n" +
	"\rGetJobRequest\x12\x14\n" +
	"\x05jobID\x18\x01 \x01(\tR\x05jobID\"6\n" +
	"\x0eGetJobResponse\x12$\n" +
	"\x03job\x18\x01 \x01(\v2\x12.nightwatch.v1.JobR\x03job\">\n" +
	"\x0eListJobRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"O\n" +
	"\x0fListJobResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12&\n" +
	"\x04jobs\x18\x02 \x03(\v2\x12.nightwatch.v1.JobR\x04jobsB7Z5github.com/LiangNing7/minerx/pkg/api/nightwatch/v1;v1b\x06proto3"

var (
	file_nightwatch_v1_job_proto_rawDescOnce sync.Once
	file_nightwatch_v1_job_proto_rawDescData []byte
)

func file_nightwatch_v1_job_proto_rawDescGZIP() []byte {
	file_nightwatch_v1_job_proto_rawDescOnce.Do(func() {
		file_nightwatch_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nightwatch_v1_job_proto_rawDesc), len(file_nightwatch_v1_job_proto_rawDesc)))
	})
	return file_nightwatch_v1_job_proto_rawDescData
}

var file_nightwatch_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_nightwatch_v1_job_proto_goTypes = []any{
	(*Job)(nil),                   // 0: nightwatch.v1.Job
	(*JobParams)(nil),             // 1: nightwatch.v1.JobParams
	(*TrainParams)(nil),           // 2: nightwatch.v1.TrainParams
	(*JobResults)(nil),            // 3: nightwatch.v1.JobResults
	(*TrainResults)(nil),          // 4: nightwatch.v1.TrainResults
	(*JobCondition)(nil),          // 5: nightwatch.v1.JobCondition
	(*CreateJobRequest)(nil),      // 6: nightwatch.v1.CreateJobRequest
	(*CreateJobResponse)(nil),     // 7: nightwatch.v1.CreateJobResponse
	(*UpdateJobRequest)(nil),      // 8: nightwatch.v1.UpdateJobRequest
	(*UpdateJobResponse)(nil),     // 9: nightwatch.v1.UpdateJobResponse
	(*DeleteJobRequest)(nil),      // 10: nightwatch.v1.DeleteJobRequest
	(*DeleteJobResponse)(nil),     // 11: nightwatch.v1.DeleteJobResponse
	(*GetJobRequest)(nil),         // 12: nightwatch.v1.GetJobRequest
	(*GetJobResponse)(nil),        // 13: nightwatch.v1.GetJobResponse
	(*ListJobRequest)(nil),        // 14: nightwatch.v1.ListJobRequest
	(*ListJobResponse)(nil),       // 15: nightwatch.v1.ListJobResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_nightwatch_v1_job_proto_depIdxs = []int32{
	1,  // 0: nightwatch.v1.Job.params:type_name -> nightwatch.v1.JobParams
	3,  // 1: nightwatch.v1.Job.results:type_name -> nightwatch.v1.JobResults
	5,  // 2: nightwatch.v1.Job.conditions:type_name -> nightwatch.v1.JobCondition
	16, // 3: nightwatch.v1.Job.createdAt:type_name -> google.protobuf.Timestamp
	16, // 4: nightwatch.v1.Job.updatedAt:type_name -> google.protobuf.Timestamp
	2,  // 5: nightwatch.v1.JobParams.train:type_name -> nightwatch.v1.TrainParams
	4,  // 6: nightwatch.v1.JobResults.train:type_name -> nightwatch.v1.TrainResults
	0,  // 7: nightwatch.v1.CreateJobRequest.job:type_name -> nightwatch.v1.Job
	1,  // 8: nightwatch.v1.UpdateJobRequest.params:type_name -> nightwatch.v1.JobParams
	3,  // 9: nightwatch.v1.UpdateJobRequest.results:type_name -> nightwatch.v1.JobResults
	0,  // 10: nightwatch.v1.GetJobResponse.job:type_name -> nightwatch.v1.Job
	0,  // 11: nightwatch.v1.ListJobResponse.jobs:type_name -> nightwatch.v1.Job
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_nightwatch_v1_job_proto_init() }
func file_nightwatch_v1_job_proto_init() {
	if File_nightwatch_v1_job_proto != nil {
		return
	}
	file_nightwatch_v1_job_proto_msgTypes[4].OneofWrappers = []any{}
	file_nightwatch_v1_job_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nightwatch_v1_job_proto_rawDesc), len(file_nightwatch_v1_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nightwatch_v1_job_proto_goTypes,
		DependencyIndexes: file_nightwatch_v1_job_proto_depIdxs,
		MessageInfos:      file_nightwatch_v1_job_proto_msgTypes,
	}.Build()
	File_nightwatch_v1_job_proto = out.File
	file_nightwatch_v1_job_proto_goTypes = nil
	file_nightwatch_v1_job_proto_depIdxs = nil
}
